const productList = [
    { name: 'Lattafa Parfum',
      recipient: 'Mom',
      age: '35-50',
      gender: 'Female',
      occasion: 'Birthday',
      interests: ['Arts','Sports','Hiking','Science','Other'],
      budget: '30-50',
      price: '45 AZN',
      description: 'A thoughtful gift for any occasion.',
      image: 'image1.jpg',
      link: 'https://umico.az/product/339752-qadinlar-uchun-etir-suyu-lattafa-perfumes-yara-100-ml'},  

    { name: 'Lattafa Parfum',
      recipient: 'Mom',
      age: '35-50',
      gender: 'Female',
      occasion: 'Birthday',
      interests: ['Arts','Sports','Hiking','Science','Other'],
      budget: '30-50',
      price: '45 AZN',
      description: 'A thoughtful gift for any occasion.',
      image: 'image1.jpg',
      link: 'https://umico.az/product/339752-qadinlar-uchun-etir-suyu-lattafa-perfumes-yara-100-ml'},     

    { name: 'Lattafa Parfum',
      recipient: 'Mom',
      age: '35-50',
      gender: 'Female',
      occasion: 'Birthday',
      interests: ['Arts','Sports','Hiking','Science','Other'],
      budget: '30-50',
      price: '45 AZN',
      description: 'A thoughtful gift for any occasion.',
      image: 'image1.jpg',
      link: 'https://umico.az/product/339752-qadinlar-uchun-etir-suyu-lattafa-perfumes-yara-100-ml'},  

    { name: 'Lattafa Parfum',
      recipient: 'Mom',
      age: '35-50',
      gender: 'Female',
      occasion: 'Birthday',
      interests: ['Arts','Sports','Hiking','Science','Other'],
      budget: '30-50',
      price: '45 AZN',
      description: 'A thoughtful gift for any occasion.',
      image: 'image1.jpg',
      link: 'https://umico.az/product/339752-qadinlar-uchun-etir-suyu-lattafa-perfumes-yara-100-ml'},    

    { name: 'Lattafa Parfum',
      recipient: 'Mom',
      age: '35-50',
      gender: 'Female',
      occasion: 'Birthday',
      interests: ['Arts','Sports','Hiking','Science','Other'],
      budget: '30-50',
      price: '45 AZN',
      description: 'A thoughtful gift for any occasion.',
      image: 'image1.jpg',
      link: 'https://umico.az/product/339752-qadinlar-uchun-etir-suyu-lattafa-perfumes-yara-100-ml'},      
];